create extension if not exists pgcrypto;
create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade,username text unique,display_name text,avatar_url text,created_at timestamptz not null default now());
create table if not exists public.tracks(id uuid primary key default gen_random_uuid(),title text not null,artist text not null,album text,cover_url text,audio_url text not null,duration_seconds integer not null default 0,genre text,created_at timestamptz not null default now());
create table if not exists public.playlists(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,name text not null,description text,cover_url text,is_public boolean not null default false,created_at timestamptz not null default now());
create table if not exists public.playlist_tracks(playlist_id uuid not null references public.playlists(id) on delete cascade,track_id uuid not null references public.tracks(id) on delete cascade,position integer not null default 0,added_at timestamptz not null default now(),primary key(playlist_id,track_id));
create table if not exists public.likes(user_id uuid not null references auth.users(id) on delete cascade,track_id uuid not null references public.tracks(id) on delete cascade,created_at timestamptz not null default now(),primary key(user_id,track_id));
create table if not exists public.play_history(id bigint generated always as identity primary key,user_id uuid not null references auth.users(id) on delete cascade,track_id uuid not null references public.tracks(id) on delete cascade,played_at timestamptz not null default now(),progress_seconds integer not null default 0);
create index if not exists tracks_search_idx on public.tracks using gin(to_tsvector('simple',coalesce(title,'')||' '||coalesce(artist,'')||' '||coalesce(album,'')));
create index if not exists history_user_time_idx on public.play_history(user_id,played_at desc);
alter table public.profiles enable row level security;alter table public.playlists enable row level security;alter table public.playlist_tracks enable row level security;alter table public.likes enable row level security;alter table public.play_history enable row level security;alter table public.tracks enable row level security;
create policy "tracks public read" on public.tracks for select using(true);
create policy "profiles public read" on public.profiles for select using(true);
create policy "own profiles" on public.profiles for all using(auth.uid()=id) with check(auth.uid()=id);
create policy "own playlists" on public.playlists for all using(auth.uid()=user_id) with check(auth.uid()=user_id);
create policy "public playlists" on public.playlists for select using(is_public=true);
create policy "playlist tracks access" on public.playlist_tracks for all using(exists(select 1 from public.playlists p where p.id=playlist_id and(p.user_id=auth.uid() or p.is_public))) with check(exists(select 1 from public.playlists p where p.id=playlist_id and p.user_id=auth.uid()));
create policy "own likes" on public.likes for all using(auth.uid()=user_id) with check(auth.uid()=user_id);
create policy "own history" on public.play_history for all using(auth.uid()=user_id) with check(auth.uid()=user_id);
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$begin insert into public.profiles(id,display_name) values(new.id,coalesce(new.raw_user_meta_data->>'full_name',split_part(new.email,'@',1))) on conflict(id) do nothing;return new;end;$$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();